Logging Doc
socotecio/django-socio-grpc pull request #212
Opened 2023-11-17 10:43 UTC by AChoffat

Add documentation for logging part

2023-11-17 10:54 UTC, AMontagu commented
I thought we agree on splitting logging into 2 parts. One in the Features folders that explain the logging system and one in the how to section explaining the way to add extra context ?
Did @legau asked change on that ?

2023-11-17 15:20 UTC, AChoffat commented
I think it's me who didn't understand that

2023-11-20 14:32 UTC, AMontagu commented on docs/features/logging.rst
> +Django-Socio-GRPC uses a system of logging based on the one used by Django.
put the link to the django doc directly

2023-11-20 14:32 UTC, AMontagu commented on docs/features/logging.rst
> +.. code-block:: python
this example may not implement solution or should not be in upur doc as junior dev can have tendancies to copy/paste example directly in code and this example does not just work out of the box.
What your opinion on that @legau

2023-11-20 14:32 UTC, AMontagu commented on docs/features/logging.rst
> +    - Lastly, if you want to log requests even if they are ok, you can launch django in DEBUG mode
replace by:
- Logging incoming request is only activated when in DEBUG mode or if LOG_OK_RESPONSE settings is set to True

2023-11-20 14:32 UTC, AMontagu commented on docs/features/logging.rst
> +                "format": 'level=%(levelname)s name=%(name)s line=%(pathname)s:%(lineno)s message="%(message)s" socio_service_name="%(socio_service_name)s" socio_action="%(socio_action)s" time=%(asct
you have specific socio context in this example. I think fmt format should not be documented in the logging features doc

2023-11-20 14:32 UTC, AMontagu commented on docs/features/logging.rst
> +                "formatter": "fmt",
use classic formatter for people to understand better

2023-11-20 14:32 UTC, AMontagu commented on docs/how-to/add-extra-context-to-logging.rst
> +            "style": "{",
why style is needed here ?

2023-11-20 14:32 UTC, AMontagu commented on docs/how-to/add-extra-context-to-logging.rst
> +            "format": "{levelname} {grpc_service_name} {grpc_action} {grpc_user_pk} {message}",
may be better to just add the extra context to the classic format for the example

2023-11-20 14:32 UTC, AMontagu commented on docs/how-to/add-extra-context-to-logging.rst
> +    def set_log_record_factory():
you don't explain how you have to call this method.
For information this method should be called before any log using the format and this should be explicitly documented IMO

2023-11-20 14:32 UTC, AMontagu commented on docs/settings.rst
> +This setting enables the logging of requests that return an OK.
should add here that the defaut behavior depend on the DEBUG settings if setting is False
And that defautl is False

2023-11-20 17:21 UTC, AMontagu commented on docs/how-to/add-extra-context-to-logging.rst
> +If you want to add information to your logs from grpc. You will need to define these two functions and call set_log_record_factory in your settings.
```suggestion
If you want to add information to your logs from grpc. You will need to define these two functions and call set_log_record_factory in your settings before any log using your formatter is called.
```

2023-11-20 17:22 UTC, AMontagu commented
waiting for last comment and @legau review and okay for me

2023-11-21 10:03 UTC, legau requested changes

2023-11-21 10:03 UTC, legau commented on docs/how-to/add-extra-context-to-logging.rst
> +    return extra_context
indentation ?

2023-11-21 10:03 UTC, legau commented on docs/how-to/add-extra-context-to-logging.rst
> +            record.grpc_service_name = ""
comment that we set a default so the formatter will not crash when this data is missing

2023-11-21 10:29 UTC, legau commented on docs/features/logging.rst
> +Django-Socio-GRPC uses a system of logging based on the one used by Django. `Documentation <https://docs.djangoproject.com/fr/4.2/topics/logging/#topic-logging-parts-loggers>`_.
```suggestion
Django-Socio-GRPC uses a system of logging based on the one used by Django. `Documentation <https://docs.djangoproject.com/en/4.2/topics/logging/#topic-logging-parts-loggers>`_.
```

2023-11-23 17:49 UTC, legau commented on docs/features/logging.rst
> +Django-Socio-GRPC by default log requests only when something goes wrong just like Django does.
Specify which logger

2023-11-24 11:51 UTC, merged